@REM install requirements
pip install telethon
pip install openpyxl 
pip install pySimplegui
pip install mysql
pip install mysql-connector-python
pip install pandas
pip install pymysql
pip install flask